#pragma once

namespace livre
{
namespace Graphics
{
    /**
     * @brief Object for initializing Vulkan and handling states.
     * 
     * Each get function should be const, so that way the InstanceObject 
     * child classes can get the information generated by Vulkan.
     */
    class RenderInstance
    {
    public:
        struct SwapChainImages
        {
            void* images;
            void* imageViews;

            uint32_t imageCount;
            void* format;
            void* extent;
        };

    private:
        // Vulkan handles
        void* instance;
        void* debugMessenger;
        void* logicalDevice;
        void* physicalDevice;
        void* surface;
        void* presentationQueue;
        void* graphicsQueue;
        void* swapChain;

        SwapChainImages* _swapChainImages;

        bool _validationSupport() const;
        void _initDebugMessenger();
        void _pickPhysicalDevice();
        void _initLogicalDevice();
        void _initSurface(void* window);
        void _createSwapChain(void* window);
        void _createImageViews();

    public:
        RenderInstance(void* window, const std::string& title = "vulkan");
        ~RenderInstance();

        const void* getLogicalDevice() const;
        const SwapChainImages& getSwapChainImages() const;

        void* makeCommandPool() const;
    };
}
}